buildup: build up
	
build:
		docker-compose -f docker-compose.yml build
up:				
		docker-compose -f docker-compose.yml up -d
inter:
		docker exec -it postgres-container psql
down:
		docker-compose -f docker-compose.yml down