version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo-container
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example


volumes:
  mongo-db:
