buildup: build up
	
build:
	docker-compose -f docker-compose.yml build
up:				
	docker-compose -f docker-compose.yml up -d
inter:
	docker exec -it mongo-container mongosh -u mongodb -p example 
down:
	docker-compose -f docker-compose.yml down